### ISSUE TITLE
You must specify your Maxmind "account_id"

### ISSUE THREAD

**Issue by juangws** [danielsreichenbach/geoip2-update#1]
**composer:**
danielsreichenbach\GeoIP2Update\ComposerClient::run
GeoIP2 database update errors:
  - You must specify your Maxmind "account_id".
  
**fix Client.php - LINE 109 Code**
if (preg_match('/^\s*(?P<name>LicenseKey|EditionIDs) ...
change 
if (preg_match('/^\s*(?P<name>AccountID|LicenseKey|EditionIDs) ...

**fix Client.php - LINE 117 Code**
$this->account_id = !empty($confParams['AccountId']) ? $confParams['AccountId'] ...
change
$this->account_id = !empty($confParams['AccountID']) ? $confParams['AccountID']

**Comment by dgaidula** [comment]
Putting this here for visibility. Just verified this fix. Can we get this merged? Thx.

**Comment by juangws** [comment]
> Putting this here for visibility. Just verified this fix. Can we get this merged? Thx.

OK.
